### PR TITLE
perl 5.22 started warning about redundant sprintf arguments

### LINKED ISSUE #2: Redundant argument in sprintf
With perl 5.22 and newer there are new warnings:

```
Redundant argument in sprintf at /opt/perl-5.22.0/lib/site_perl/5.22.0/Class/Field.pm line 59.
```

Seen while running the test suite of Test::HTTP.

### PR DESCRIPTION
**Pull request by mtmail**
This fixes https://github.com/ingydotnet/class-field-pm/issues/2

Before

```
$ prove -lr test/
test/anon.t ... Redundant argument in sprintf at lib/Class/Field.pm line 59.
test/anon.t ... ok
test/const.t .. ok
test/field.t .. Redundant argument in sprintf at /home/vagrant/class-field-pm/lib/Class/Field.pm line 59.
test/field.t .. ok
All tests successful.
```

After

```
$ prove -lr test/
test/anon.t ... ok
test/const.t .. ok
test/field.t .. ok
All tests successful.
```

Travis output Perl 5.8-5.24 https://travis-ci.org/mtmail/class-field-pm/builds/181059666

### CODE REVIEW

**Comment by horgh** [comment]
The warning happens in Perl 5.26.1 and 5.26.2 too. This PR resolves it.

Here's a small program that causes the warning:

```perl                                                                                                                                                
use strict;                                                                                                                                                                          
use warnings;

use Class::Field 'field';

field 'test', -init => '$self->hello';
```

**Comment by freyfogle** [comment]
any hope of getting this patch live? Thanks

**Comment by oalders** [comment]
Hi @ingydotnet! This is affecting us at $work. Anything we can do to help expedite getting this released?

**Comment by ingydotnet** [comment]
Thanks and sorry for the wait. @oalders pinged me on IRC, which was a pretty smart idea...

**Pull request merged**
